### PR TITLE
[PECOBLR-624][ES-1522003] remove exception for invalid state scenario

### LINKED ISSUE #885: [BUG] Closing connection with invalid session handle throws
**Describe the bug**
If a connection is allowed to live past max session length then invoking `close()` throws a checked exception through a proxy. See stacktrace below. This is somehow preventing our Agroal pool from evicting connections.

The setup for us is we manage connections to databricks via an Agroal pool. We have a low reap timeout (14 minutes, so we should be lower than the cluster's `spark.hadoop.hive.server2.idle.session.timeout`) yet still frequently hit this with one of our clients.

**To Reproduce**
Create connections in an agroal pool and allow them to go past their session timeout.

**Expected behavior**
close() should not throw an unspecified checked exception.

**Screenshots**

**Client side logs**
```
<partner stacktrace snippet excluded>
Caused by: java.lang.reflect.UndeclaredThrowableException
	at jdk.proxy2/jdk.proxy2.$Proxy186.deleteSession(Unknown Source)
	at com.databricks.jdbc.api.impl.DatabricksSession.close(DatabricksSession.java:159)
	at com.databricks.jdbc.api.impl.DatabricksConnection.close(DatabricksConnection.java:155)
	at io.agroal.pool.util.XAConnectionAdaptor.close(XAConnectionAdaptor.java:33)
	at io.agroal.pool.ConnectionHandler.closeConnection(ConnectionHandler.java:178)
	at io.agroal.pool.ConnectionPool$DestroyConnectionTask.run(ConnectionPool.java:799)
	at io.agroal.pool.ConnectionPool.close(ConnectionPool.java:200)
	at io.agroal.pool.DataSource.close(DataSource.java:79)
	at <partner stacktrace snippet excluded>
	... 14 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.databricks.jdbc.telemetry.latency.DatabricksMetricsTimedProcessor$TimedInvocationHandler.invoke(DatabricksMetricsTimedProcessor.java:45)
	... 23 more
	Caused by: com.databricks.jdbc.exception.DatabricksSQLException: Error while receiving response from Thrift server. Request {TCloseSessionReq(sessionHandle:TSessionHandle(sessionId:THandleIdentifier(guid:01 F0 54 2D 23 B9 16 A7 87 DA 1C 29 D7 13 92 C9, secret:33 8D 52 9D 82 72 46 EB 84 82 CB 41 94 66 83 9D)))}, Error {Failed to flush data to server: HTTP request failed by code: 400, status line: HTTP/1.1 400 Bad Request.Thrift Header : INVALID_STATE: Invalid SessionHandle: SessionHandle [01f0542d-23b9-16a7-87da-1c29d71392c9].}
	at com.databricks.jdbc.dbclient.impl.thrift.DatabricksThriftAccessor.getThriftResponse(DatabricksThriftAccessor.java:175)
	at com.databricks.jdbc.dbclient.impl.thrift.DatabricksThriftServiceClient.deleteSession(DatabricksThriftServiceClient.java:131)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 25 more
	Caused by: com.databricks.internal.apache.thrift.transport.TTransportException: Failed to flush data to server: HTTP request failed by code: 400, status line: HTTP/1.1 400 Bad Request.Thrift Header : INVALID_STATE: Invalid SessionHandle: SessionHandle [01f0542d-23b9-16a7-87da-1c29d71392c9].
	at com.databricks.jdbc.dbclient.impl.thrift.DatabricksHttpTTransport.flush(DatabricksHttpTTransport.java:155)
	at com.databricks.internal.apache.thrift.TServiceClient.sendBase(TServiceClient.java:75)
	at com.databricks.internal.apache.thrift.TServiceClient.sendBase(TServiceClient.java:64)
	at com.databricks.jdbc.model.client.thrift.generated.TCLIService$Client.send_CloseSession(TCLIService.java:237)
	at com.databricks.jdbc.model.client.thrift.generated.TCLIService$Client.CloseSession(TCLIService.java:230)
	at com.databricks.jdbc.dbclient.impl.thrift.DatabricksThriftAccessor.getThriftResponse(DatabricksThriftAccessor.java:107)
```

**Client Environment (please complete the following information):**
 - OS: Linux
 - Java version Java 21
 - Java vendor Corretto
 - Driver Version oss-1.0.7
 - BI Tool (if used) Explo (ISV partner, submitter)
 - BI Tool version (if applicable) [e.g. 24.3.5]

**Additional context**

### PR DESCRIPTION
**Pull request by shivam2680**
## Description

DatabricksSession.close() shouldn’t fail when the session is already gone – closing an already-closed resource must be idempotent.
Fixes #885 

### reproduction:
1. send any request to compute
2. terminate and re-start the compute before sending the next request, invalidating all active sessions
3. call conn.close() after compute re-starts again.

### Issue:

Calls to proxied thrift client methods that are not annotated with @DatabricksMetricsTimed (e.g., deleteSession) incorrectly threw an UndeclaredThrowableException on failure. The root cause was inconsistent exception handling in TimedInvocationHandler, which did not unwrap the InvocationTargetException for non-annotated methods, forcing the proxy to wrap it and hide the original exception from the caller.

### Fix:

This PR corrects the bug in TimedInvocationHandler by wrapping all method invocations in a universal try...catch block. This block specifically catches InvocationTargetException for both annotated and non-annotated methods and re-throws the original underlying exception via e.getCause(). This ensures the proxy is transparent for all exceptions, allowing them to be caught correctly by the calling code.

## Testing

Created a new compute for testing
Followed reproduction mechanism and driver successfully swallowed the exception under invalid session and scenario and issued warning log.

### CODE REVIEW

File: src/main/java/com/databricks/jdbc/api/impl/DatabricksSession.java [hunk 1]
```diff
@@ -156,9 +157,21 @@ public void close() throws DatabricksSQLException {
...
-        this.isSessionOpen = false;
+        try {
+          databricksClient.deleteSession(sessionInfo);
+        } catch (DatabricksSQLException e) {
+          if (e.getMessage() != null && e.getMessage().contains(INVALID_SESSION_STATE_MSG)) {
+            LOGGER.info(
+                "Session [{}] already expired/invalid on server – ignoring during close()",
+                sessionInfo.sessionId());
+          } else {
+            throw e;
```
[the remark this answers is not in the document]
Comment (shivam2680) [reply src/main/java/com/databricks/jdbc/api/impl/DatabricksSession.java:168]: If the error message contains anything other than invalid state message

**Comment by gboehringer** [comment]
Our team is tracking this one closely - looking forward to the impact this will have for our customers at Explo.

File: src/main/java/com/databricks/jdbc/telemetry/latency/DatabricksMetricsTimedProcessor.java [hunk 2]
```diff
@@ -26,23 +27,22 @@ public TimedInvocationHandler(T target) {
...
-          // Calculate execution time
           long executionTime = System.currentTimeMillis() - startTime;
-          exportLatencyLog(executionTime);
+          exportLatencyLog(executionTime); // Log is exported ONLY here.
           return result;
-        } catch (Throwable throwable) {
-          // Handle exceptions from the target method
-          throw throwable.getCause() != null ? throwable.getCause() : throwable;
+        } else {
+          // For methods like deleteSession(), this block is executed.
```
Comment (samikshya-db) [inline src/main/java/com/databricks/jdbc/telemetry/latency/DatabricksMetricsTimedProcessor.java:38]: delete session would also have the metrics annotation present ideally : https://github.com/databricks/databricks-jdbc/blob/d337384fab106ee395565d2b6b8705ca9fe301c4/src/main/java/com/databricks/jdbc/dbclient/IDatabricksClient.java#L44 here. Can you please add it and test too? 

Thanks for doing this!

Comment (shivam2680) [reply src/main/java/com/databricks/jdbc/telemetry/latency/DatabricksMetricsTimedProcessor.java:38]: tested.

warning log printed.
2025-07-16 15:07:19 WARNING com.databricks.jdbc.api.impl.DatabricksSession#close - Session [1b4dcaa1-dbe2-48f3-1b4d-caa1dbe248f3] already expired/invalid on server – ignoring during close()

Comment (samikshya-db) [reply src/main/java/com/databricks/jdbc/telemetry/latency/DatabricksMetricsTimedProcessor.java:38]: Update the comment as well? `For methods like deleteSession(), this block is executed.`

Comment (shivam2680) [reply src/main/java/com/databricks/jdbc/telemetry/latency/DatabricksMetricsTimedProcessor.java]: Just resolved merge conflicts, can you verify if the `DatabricksMetricsTimedProcessor` looks correct

Comment (samikshya-db) [reply src/main/java/com/databricks/jdbc/telemetry/latency/DatabricksMetricsTimedProcessor.java]: Beautiful, feel free to merge it
