### PR TITLE
Add fix for incorrect timestamp issue

### LINKED ISSUE #1116: [BUG] DatabricksPreparedStatement#setTimestamp(int, java.sql.Timestamp, java.util.Calendar) truncates microseconds part
**Describe the bug**
It looks like `com.databricks.jdbc.api.impl.DatabricksPreparedStatement#setTimestamp(int, java.sql.Timestamp, java.util.Calendar)` method truncates microseconds part from the timestamp when setting the query parameter, while Databricks itself support microseconds in timestamps.
This is critical because we are using timestamps we are getting from the DB to query next chunks of data. So this behaviour makes our system re-read the same records in loop.

**To Reproduce**
1. Create a table with timestamp column
2. Execute smth like:
```
try (Connection conn = DriverManager.getConnection(url)) {
	// Build a timestamp with microsecond precision
	Timestamp originalTs = Timestamp.valueOf("2025-11-21 23:30:49.185645");
	// Ensure nanos are exactly what we expect (Spark uses microsecond precision)
	originalTs.setNanos(185_645_000);
	// Calendar matching Kafka Connect style (timestamp with time zone awareness)
	Calendar calendar = Calendar.getInstance(TimeZone.getTimeZone("UTC"));
	// Update existing row using PreparedStatement#setTimestamp with Calendar
	try (PreparedStatement ps = conn.prepareStatement(updateSql)) {
	        ps.setTimestamp(1, originalTs, calendar);
	        LOGGER.info("Executing update with PreparedStatement#setTimestamp and Calendar");
		int updated = ps.executeUpdate();
    }
}
``` 
with `LogLevel=5`
3. Check logs

**Expected behavior**
Timestamp parameter is set as is.
**Actual behavior**
Timestamp parameter is truncated to milliseconds precision:
```
[main] INFO com.tealium.jdbc.DatabricksDriverTest - Original Timestamp before setTimestamp: 2025-11-21 23:30:49.185645 (nanos = 185645000)
[main] INFO com.tealium.jdbc.DatabricksDriverTest - Executing update with PreparedStatement#setTimestamp and Calendar
[main] INFO com.tealium.jdbc.DatabricksDriverTest - Round-tripped JDBC Timestamp: 2025-11-21 23:30:49.185 (nanos = 185000000)
2025-11-28 15:19:41 FINE com.databricks.jdbc.dbclient.impl.thrift.DatabricksThriftServiceClient#executeStatement - public DatabricksResultSet executeStatement(String sql = {UPDATE vzh_test SET ts = ? WHERE id = 2}, Compute cluster = {SQL Warehouse with warehouse ID {...}}, Map<Integer, ImmutableSqlParameter> parameters = {{1=SqlParameter{value=2025-11-21 23:30:49.185, type=TIMESTAMP, cardinal=1}}}, StatementType statementType = {UPDATE}, IDatabricksSession session)
```

**Client Environment (please complete the following information):**
- OS: MacOS
- Java version: Java 17
- Java vendor: graalvm
- Driver Version 1.0.11-oss

**Additional context**
Simba's version seems to process this case correctly without truncating microseconds part:
`Nov 28 16:26:12.329 DEBUG 1 com.databricks.client.hivecommon.dataengine.HiveJDBCNativeQueryExecutor.executeHelperParameter: The spark parameters for parameterized query are  [TSparkParameter(ordinal:1, type:TIMESTAMP, value:<TSparkParameterValue stringValue:2025-11-21 23:30:49.185645>)]`

### PR DESCRIPTION
**Pull request by samikshya-db**
## Description
Fixes #1116 

## Testing
Tested E2E using the following test  (also verified that the legacy driver has the same behavior)

```
  @Test
  void example_TimestampMicrosecondPrecisionWithCalendar() throws Exception {
    //create connection first.
    try {
      String tableName = "default.samikshyananosecondtesting";
      Statement stmt = con.createStatement();
      stmt.execute(
          "CREATE TABLE IF NOT EXISTS " + tableName + " (id INT, ts TIMESTAMP) USING DELTA");
      System.out.println("Created test table: " + tableName);

      String insertSql = "INSERT INTO " + tableName + " VALUES (?, ?)";
      PreparedStatement pstmt = con.prepareStatement(insertSql);

      java.sql.Timestamp originalTs = java.sql.Timestamp.valueOf("2025-11-21 23:30:49.185645");
      assertEquals(
          185645000, originalTs.getNanos(), "Original timestamp should have microsecond precision");

      pstmt.setInt(1, 1);
      java.util.Calendar utcCalendar =
          java.util.Calendar.getInstance(java.util.TimeZone.getTimeZone("UTC"));
      pstmt.setTimestamp(2, originalTs, utcCalendar);
      pstmt.executeUpdate();
      System.out.println("Inserted timestamp with microsecond precision: " + originalTs);

      ResultSet rs = stmt.executeQuery("SELECT id, ts FROM " + tableName + " WHERE id = 1");
      if (rs.next()) {
        java.sql.Timestamp retrievedTs = rs.getTimestamp(2);
        System.out.println("Retrieved timestamp: " + retrievedTs);
        System.out.println("Retrieved nanoseconds: " + retrievedTs.getNanos());

        assertEquals(
            185645000,
            retrievedTs.getNanos(),
            "Microsecond precision should be preserved (issue #1116 fix verification)");
        System.out.println("✓ Microsecond precision preserved successfully!");
      }
      rs.close();

      stmt.execute("DROP TABLE IF EXISTS " + tableName);
      System.out.println("Cleaned up test table");

      pstmt.close();
      stmt.close();
    } finally {
      con.close();
      System.out.println("Connection closed");
    }
  }
```

### CODE REVIEW

File: src/test/java/com/databricks/jdbc/api/impl/DatabricksPreparedStatementTest.java [hunk 1]
```diff
@@ -1209,4 +1209,76 @@ public void testRejectsZeroBatchSize() throws Exception {
         exception.getMessage().contains("Invalid value for BatchInsertSize"),
         "Exception should mention invalid BatchInsertSize: " + exception.getMessage());
   }
+
+  @Test
+  public void testSetTimestampWithCalendarPreservesMicroseconds() throws Exception {
```
Comment (AndreiRudkouski) [inline src/test/java/com/databricks/jdbc/api/impl/DatabricksPreparedStatementTest.java]: The test does not actually validate the result, because the expected value is calculated using the same logic as the implementation, so any incorrect behavior may remain unnoticed.

Comment (samikshya-db) [reply src/test/java/com/databricks/jdbc/api/impl/DatabricksPreparedStatementTest.java]: Thanks @AndreiRudkouski, I ran it in IST (in my local that is). Appreciate your feedback.

File: src/main/java/com/databricks/jdbc/api/impl/DatabricksPreparedStatement.java [hunk 2]
```diff
@@ -441,11 +441,23 @@ public void setTimestamp(int parameterIndex, Timestamp x, Calendar cal) throws S
...
+      targetCalendar.set(Calendar.DAY_OF_MONTH, defaultCalendar.get(Calendar.DAY_OF_MONTH));
+      targetCalendar.set(Calendar.HOUR_OF_DAY, defaultCalendar.get(Calendar.HOUR_OF_DAY));
+      targetCalendar.set(Calendar.MINUTE, defaultCalendar.get(Calendar.MINUTE));
+      targetCalendar.set(Calendar.SECOND, defaultCalendar.get(Calendar.SECOND));
+      targetCalendar.set(
+          Calendar.MILLISECOND, 0); // Because we are already handling sub-second precision below
+
+      Timestamp convertedTimestamp = new Timestamp(targetCalendar.getTimeInMillis());
+      convertedTimestamp.setNanos(
+          x.getNanos()); // Note this preserved the microseconds and nanoseconds both
```
Comment (gopalldb) [inline src/main/java/com/databricks/jdbc/api/impl/DatabricksPreparedStatement.java]: Good!
