### PR TITLE
[PECOBLR-839] Fixed getString for boolean column

### LINKED ISSUE #956: [BUG] - DatabaseMetadata.getTypeInfo is empty versus SIMBA driver for Databricks
When mutual customers encounter issues with a 3rd party, they frequently will use other tools such as SQLSquirrel to triage topics.

Having connected to Databricks, the UX to display the response from DatabaseMetadata.getTypeInfo is blank vs non-empty when they use the SIMBA JDBC driver.

OSS JDBC driver version 109

When a connection is established to Databaricks using a tool such as SQLSquirrel, the response from DatabaseMetadata.getTypeInfo is empty.

A grid of type information is returned when the SIMBA driver is used.

 
OSS driver/SQLSquirrel

Image

SIMBA driver 273/SQL Squirrel

Image

A Java program may see type Info

Vendor name(TINYINT) JDBC Type (-6,TINYINT) Precision(3) Scale(0,0) Prefix(null), Suffix(null) can map to(Smallint)
Vendor name(BIGINT) JDBC Type (-5,BIGINT) Precision(19) Scale(0,0) Prefix(null), Suffix(null) can map to(Bigint)
Vendor name(BINARY) JDBC Type (-2,BINARY) Precision(32767) Scale(null,null) Prefix(0x), Suffix(null) can map to(Binary)
Vendor name(CHAR) JDBC Type (1,CHAR) Precision(255) Scale(null,null) Prefix('), Suffix(') can map to(Char)
Vendor name(DECIMAL) JDBC Type (3,DECIMAL) Precision(38) Scale(0,0) Prefix(null), Suffix(null) can map to(Decimal)
Vendor name(INT) JDBC Type (4,INTEGER) Precision(10) Scale(0,0) Prefix(null), Suffix(null) can map to(Integer)
Vendor name(SMALLINT) JDBC Type (5,SMALLINT) Precision(5) Scale(0,0) Prefix(null), Suffix(null) can map to(Smallint)
Vendor name(FLOAT) JDBC Type (6,FLOAT) Precision(7) Scale(null,null) Prefix(null), Suffix(null) can map to(Float)
Vendor name(DOUBLE) JDBC Type (8,DOUBLE) Precision(15) Scale(null,null) Prefix(null), Suffix(null) can map to(Double)
Vendor name(ARRAY) JDBC Type (12,VARCHAR) Precision(32767) Scale(null,null) Prefix('), Suffix(') can map to(Varchar)
Vendor name(MAP) JDBC Type (12,VARCHAR) Precision(32767) Scale(null,null) Prefix('), Suffix(') can map to(Varchar)
Vendor name(STRING) JDBC Type (12,VARCHAR) Precision(510) Scale(null,null) Prefix('), Suffix(') can map to(Varchar)
Vendor name(STRUCT) JDBC Type (12,VARCHAR) Precision(32767) Scale(null,null) Prefix('), Suffix(') can map to(Varchar)
Vendor name(VARCHAR) JDBC Type (12,VARCHAR) Precision(510) Scale(null,null) Prefix('), Suffix(') can map to(Varchar)
Vendor name(VARIANT) JDBC Type (12,VARCHAR) Precision(32767) Scale(null,null) Prefix('), Suffix(') can map to(Varchar)
Vendor name(BOOLEAN) JDBC Type (16,BOOLEAN) Precision(1) Scale(null,null) Prefix(null), Suffix(null) can map to(Boolean)
Vendor name(DATE) JDBC Type (91,DATE) Precision(10) Scale(null,null) Prefix('), Suffix(') can map to(Date)
Vendor name(TIMESTAMP) JDBC Type (93,TIMESTAMP) Precision(29) Scale(0,0) Prefix('), Suffix(') can map to(Timestamp)
Vendor name(TIMESTAMP_NTZ) JDBC Type (93,TIMESTAMP) Precision(29) Scale(0,0) Prefix('), Suffix(') can map to(Timestamp)
Vendor name(INTERVAL) JDBC Type (12,VARCHAR) Precision(40) Scale(0,6) Prefix('), Suffix(') can map to(Varchar)

### PR DESCRIPTION
**Pull request by msrathore-db**
## Description

Added a toString function in BITConverter to fix getString for boolean columns. Fixed toBoolean to handle null. Added tests for both the functions of BITConverter
## Testing

Added unit tests
## Additional Notes to the Reviewer

Fixes #956

### CODE REVIEW

File: src/main/java/com/databricks/jdbc/api/impl/converters/BitConverter.java [hunk 1]
```diff
@@ -17,7 +17,17 @@ public boolean toBoolean(Object object) throws DatabricksSQLException {
...
         DatabricksDriverErrorCode.UNSUPPORTED_OPERATION);
   }
+
+  @Override
+  public String toString(Object object) throws DatabricksSQLException {
+    if (object instanceof Boolean) {
+      return object.toString();
+    }
+    // For other types, fall back to the default behavior
+    throw new DatabricksSQLException(
```
Comment (shivam2680) [inline src/main/java/com/databricks/jdbc/api/impl/converters/BitConverter.java:30]: should throw error message same as above method.
```
        "Unsupported type for conversion to BIT: " + (object == null ? "null" : object.getClass()),
```

**Review by shivam2680 — APPROVED** [review]
Please run the repro steps mentioned in ticket to confirm the fix!

File: src/main/java/com/databricks/jdbc/api/impl/converters/BitConverter.java (hunk 1 above)
Comment (msrathore-db) [reply src/main/java/com/databricks/jdbc/api/impl/converters/BitConverter.java:29]: Updated
